# Generated by Django 2.2 on 2019-12-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191223_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AddField(
            model_name='profile',
            name='u_followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='u_following',
            field=models.ManyToManyField(blank=True, related_name='following', to='accounts.Profile'),
        ),
    ]
