# Generated by Django 2.2 on 2019-12-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191223_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='u_followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='u_following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='accounts.Profile'),
        ),
    ]
