# Generated by Django 2.2 on 2019-12-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191223_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='u_following',
            new_name='follows',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='u_followers',
        ),
    ]
