# Generated by Django 2.2 on 2019-12-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191227_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_active',
            new_name='email_confirm',
        ),
    ]
